#!/bin/bash

source ~/etc/bspwm/panel_config

PANEL_WM_NAME="${PANEL_WM_NAME}-$1"
PANEL_FIFO="${PANEL_FIFO}.$1"

if xdo id -a "$PANEL_WM_NAME" > /dev/null;
then
    printf "%s\n" "Panel $1 is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

echo "B" "$(acpi --battery | cut -d, -f2 | sed 1q)" > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
clock -sf 'S%y-%m-%d %w %H:%M:%S' > "$PANEL_FIFO" &
bspc subscribe report > "$PANEL_FIFO" &

[ $1 == "1" ] && ddate "+D%{%A, %e of %B%}, %Y YOLD%N [%H]" > "$PANEL_FIFO" &

~/etc/bspwm/panel_bar < "$PANEL_FIFO" | \
    lemonbar -a 32 -u 2 -n "$PANEL_WM_NAME" \
	     -g $2x"$PANEL_HEIGHT"+$3 -f "$PANEL_FONT" \
	     -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" \
    | bash &

xdo above -t "$(xdo id -N Bspwm -n root | sort | sed 1q)" "$(xdo id -m -a $PANEL_WM_NAME | sort | sed 1q)"

wait
