# -*- sh -*-
setopt allexport

## General config

# me
NAME="Erkin Batu Altunbaş"
EMAIL="$(base64 --decode <<< 'bWVAZXJraW4ucGFydHkK')"
ORGANIZATION=""

# editor
EDITOR="emacsclient -c"
ALTERNATE_EDITOR="emacs"
SUDO_EDITOR="emacsclient -t"
VISUAL="emacsclient -c"

# locale
LANG="en_DK.UTF-8"
TZ="TRT-3"

# misc
ARCH="x86_64"
ARCHFLAGS="-arch $ARCH"
BROWSER="firefox"
WWW_HOME="https://start.duckduckgo.com/lite"
COLORTERM="truecolor"
PAGER="less"

# xdg dirs
XDG_CONFIG_HOME="$HOME/etc"
XDG_DATA_HOME="$HOME/usr/share"
XDG_CACHE_HOME="$HOME/var/cache"
#XDG_RUNTIME_DIR="$HOME/var/run"
XDG_RUNTIME_DIR="/run/user/$(id -u)"


## Application-specific config

# bat
BAT_THEME="1337"

# ccache
CCACHE_PATH="/usr/bin"
CCACHE_CONFIG_PATH="$XDG_CONFIG_HOME/ccache/ccache.conf"
CCACHE_DIR="$XDG_CACHE_HOME/ccache"

# CVS
CVS_PASSFILE="$XDG_DATA_HOME/cvspass"

# elinks
ELINKS_CONFDIR="$XDG_CONFIG_HOME/elinks"

# figlet
FIGLET_FONTDIR="/usr/share/figlet:/usr/share/figlet/fonts:$XDG_DATA_HOME/figlet"

# gcc
GCC_COLORS="error=01;31:warning=01;35:note=01;36:range1=32:range2=34:locus=01:\
            quote=01:fixit-insert=32:fixit-delete=31:type-diff=01;3:\
            diff-filename=01:diff-hunk=32:diff-delete=31:diff-insert=32:"

# grep
GREP_COLOR="1;32"

# git
GIT_EDITOR="$SUDO_EDITOR"
GIT_PAGER="$PAGER"

# gpg
GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

# gramps
GRAMPSHOME="$XDG_DATA_HOME/gramps"

# GTK+
GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
GTK_IM_MODULE="fcitx"

# less
LESS="-FJMQSReis"
LESS_TERMCAP_mb=$(printf "\e[1;31m")
LESS_TERMCAP_md=$(printf "\e[1;31m")
LESS_TERMCAP_me=$(printf "\e[0m")
LESS_TERMCAP_se=$(printf "\e[0m")
LESS_TERMCAP_so=$(printf "\e[1;44;33m")
LESS_TERMCAP_ue=$(printf "\e[0m")
LESS_TERMCAP_us=$(printf "\e[1;32m")
LESSHISTFILE="$XDG_CONFIG_HOME/less/history"
LESSKEY="$XDG_CONFIG_HOME/less/lesskey"
LESSEDIT="$SUDO_EDITOR ?lm+%lm. %f"
#LESSSECURE=0
#LESSOPEN="| src-hilite-lesspipe.sh %s"
#LESS_ADVANCED_PREPROCESSOR=1

# lynx
LYNX_CFG_PATH="$XDG_CONFIG_HOME/lynx"

# mail
MAILCAP="$XDG_CONFIG_HOME/mailcap"
MAILCAPS="$MAILCAP"
MBOX="$HOME/var/mbox"
MU_HOME="$XDG_CACHE_HOME/mu"

# man
MANPAGER="$PAGER"
MANLESS='\ \$MAN_PN\ ?ltL%lt?L/%L.:B%bB?B/%B..?e\ E:?pB\ %pB\%..'

# mc
MC_XDG_OPEN="$HOME/usr/bin/nohup-open"

# mplayer
MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"

# MySQL
MYSQL_HISTFILE="$XDG_DATA_HOME/mysql/history"

# nnn
NNN_USE_EDITOR=1
NNN_BMS="tmp:~/tmp"
NNN_COPIER="~/usr/bin/copier.sh"
NNN_TMPFILE="/tmp/nnn"

# NVIDIA
CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"

# parallel
PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"

# PulseAudio
#PULSE_LATENCY_MSEC=60

# Qemu
QEMU_AUDIO_DRV="pulse"

# Qt
QT_IM_MODULE="fcitx"
QT_QPA_PLATFORMTHEME="gtk2"
QT_QPA_PLATFORMTHEME="qt5ct"
QT_STYLE_OVERRIDE="gtk2"

# readline
INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
RLWRAP_HOME="$XDG_CONFIG_HOME/readline/hist"
RLWRAP_EDITOR="emacsclient -c +%L:%C %F"

# rxvt
#RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"

# SDL
SDL_VIDEO_FULLSCREEN_HEAD=1
SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
SDL_VIDEO_X11_DGAMOUSE=0
SDL_AUDIO_DRIVER="pulse"

# ssh
SSH_KEY_PATH="$HOME/.ssh/rsa_id" # Sad!
SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

# Subversion
SVN_I_LOVE_PANGALACTIC_GARGLE_BLASTERS=1

# systemd
SYSTEMD_PAGER="bat"

# wget
WGETRC="$XDG_CONFIG_HOME/wgetrc"

# wine
WINEDLLOVERRIDES="mscoree,mshtml="
WINEPREFIX="$XDG_DATA_HOME/wine/default"

# Xorg
XCOMPOSEFILE="$XDG_CONFIG_HOME/X11/XCompose"
XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"
XCURSOR_THEME="Hackneyed"
XMODIFIERS="@im=fcitx"
XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
ICEAUTHORITY="$XDG_RUNTIME_DIR/ICEauthority"
XKB_DEFAULT_MODEL="logitech_base"
XKB_DEFAULT_LAYOUT="meow"
#XKB_DEFAULT_VARIANT=""
XKB_DEFAULT_OPTIONS="compose:caps,terminate:ctrl_alt_bksp"

# zsh
YSU_MESSAGE_FORMAT="\e[31m%alias_type for %command: %alias\e[0m"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

## Language-specific config

# Carp
CARP_DIR="$HOME/dev/repos/Carp"

# Clojure
LEIN_HOME="$XDG_DATA_HOME/lein"

# Haskell
STACK_ROOT="$XDG_DATA_HOME/stack"
CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"

# Java
_JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME/java\""
_JAVA_AWT_WM_NONREPARENTING=1

# OCaml
OPAMROOT="$XDG_DATA_HOME/opam"
OPAM_SWITCH_PREFIX="$OPAMROOT/system"
OCAML_TOPLEVEL_PATH="$OPAM_SWITCH_PREFIX/lib/toplevel"
CAML_LD_LIBRARY_PATH="$OPAM_SWITCH_PREFIX/lib/stublibs:/usr/lib/ocaml/stublibs"

# Octave
OCTAVE_HISTFILE="$XDG_CONFIG_HOME/octave/octave_hist"
OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"

# Perl
PERL5LIB="$XDG_DATA_HOME/perl5/lib/perl5:$OPAM_SWITCH_PREFIX/lib/perl5:$PERL5LIB"
PERL_LOCAL_LIB_ROOT="$XDG_DATA_HOME/perl5:$PERL_LOCAL_LIB_ROOT"
PERL_MB_OPT="--install_base \"$XDG_DATA_HOME/perl5\""
PERL_MM_OPT="INSTALL_BASE=$XDG_DATA_HOME/perl5"

# Python
PYTHONSTARTUP="$XDG_CONFIG_HOME/python/startup.py"
PYLINTHOME="$XDG_CACHE_HOME/pylint"
WORKON_HOME="$HOME/dev/envs"
PYTHONDONTWRITEBYTECODE=1

# Racket
PLT_PKG_SSL_NO_VERIFY=1 # ugh

# Ruby
GEM_HOME="$XDG_DATA_HOME/gem"
GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"

# Rust
CARGO_HOME="$XDG_DATA_HOME/cargo"
RUSTUP_HOME="$XDG_DATA_HOME/rustup"
RUST_SRC_PATH="$HOME/dev/repos/rust/src"


## Game-specific config

# Dungeon Crawl
CRAWL_DIR="$XDG_DATA_HOME/crawl/"

# nethack
NETHACKOPTIONS="@$XDG_CONFIG_HOME/nethack/nethackrc" # @ is mandatory


unsetopt allexport

