# -*- sh -*-

#[[ $TERM = linux ]] && fbset -g 1920 1080 1920 1080 32

setopt allexport

XDG_CONFIG_HOME="$HOME/etc"
XDG_DATA_HOME="$HOME/usr/share"
XDG_CACHE_HOME="$HOME/var/cache"
#XDG_RUNTIME_DIR="$HOME/var/run"
XDG_RUNTIME_DIR="/run/user/$(id -u)"

source "$XDG_CONFIG_HOME/user-dirs.dirs"

unsetopt allexport
