#!/bin/bash

# bgd()
# {
# 	pidof $1 >& /dev/null
# 	if [ $? -ne 0 ]; then
# 		$@ &
# 	fi
# }

## Xorg stuff
xsetroot -cursor_name left_ptr
xset -dpms; xset s off
xset +fp $XDG_DATA_HOME/fonts/bitmap
xinput --set-prop "ImExPS/2 Generic Explorer Mouse" "libinput Accel Speed" -0.5
fcitx -d
setxkbmap -layout meow -option compose:caps,terminate:ctrl_alt_bksp
[[ -f ~/etc/X11/Xresources ]] && xrdb -merge -I$HOME $XDG_CONFIG_HOME/X11/Xresources
[[ -f ~/etc/X11/Xmodmap ]] && xmodmap $XDG_CONFIG_HOME/X11/Xmodmap
# g610-led -p ~/src/profile &

## Make sure Emacs daemon is launched only once
pidof emacs >& /dev/null
if [ $? -ne 0 ];
then
    env GTK_IM_MODULE=xim XMODIFIERS=@im=none \
	dbus-launch --sh-syntax emacs --daemon &!
fi

autocutsel -fork &
autocutsel -selection PRIMARY -fork &
# compton --paint-on-overlay --unredir-if-possible --backend xr_glx_hybrid\
#	--vsync opengl-mswc --glx-swap-method -1 --glx-no-stencil -b
xcompmgr -FfCc -D 3 2>/dev/null &

## Generate a randomly tiled wallpaper
SUIKA="~/media/image/suika"
montage $(no -1 $SUIKA/*1200.jpg | sort -R) -mode concatenate -tile 8x5 $SUIKA/result.jpg && feh --bg-tile $SUIKA/result.jpg

exec dbus-launch --exit-with-session --sh-syntax awesome
