(defvar holiday-discordian-holydays
  '((holiday-fixed  1  5   "Mungday")
    (holiday-fixed  2 19   "Chaoflux")
    (holiday-fixed  2 29   "St Tib's Day")
    (holiday-fixed  3 19   "Mojoday")
    (holiday-fixed  3 25   "Jesus Day")
    (holiday-fixed  4  6   "Jake Day")
    (holiday-fixed  5  3   "Discoflux")
    (holiday-fixed  5 21   "St Camping's Day")
    (holiday-fixed  5 23   "Jake Day Jr")
    (holiday-fixed  5 25   "Towel Day")
    (holiday-fixed  5 31   "Syaday")
    (holiday-fixed  7  2   "Midyearsday")
    (holiday-fixed  7  5   "X-Day")
    (holiday-fixed  7 15   "Confuflux")
    (holiday-fixed  8  8   "\"Bob\"day")
    (holiday-fixed  8 12   "Zaraday")
    (holiday-fixed  9 26   "Bureflux")
    (holiday-fixed 10 24   "Maladay")
    (holiday-fixed 12  8   "Afflux")))

(defvar holiday-nerd-holidays
  '((holiday-fixed  1  1   "Public Domain Day")
    (holiday-fixed  1  2   "Science Fiction Day")
    (holiday-fixed  1 15   "Wikipedia Day")
    (holiday-fixed  1 28   "Data Privacy Day")
    (holiday-fixed  2 13   "Radio Day")
    (holiday-fixed  3 25   "Tolkien Reading Day")
    (holiday-fixed  3 31   "Backup Day")
    (holiday-fixed  4 12   "Yuri's Night")
    (holiday-fixed  6 16   "Bloomsday")
    (holiday-fixed  7 17   "Emoji Day")
    (holiday-float  7 5 -1 "System Administrator Appreciation Day")
    (holiday-float  8 3  1 "Engineers' Day")
    (holiday-float  9 6  3 "Software Freedom Day")
    (holiday-fixed  9  6   "Literacy Day")
    (holiday-fixed  9 13   "Programmers' Day")
    (holiday-float 10 2  2 "Ada Lovelace Day")
    (holiday-fixed 11 30   "Computer Security Day")
    (holiday-fixed 12 11   "Shareware Day")))

(defvar holiday-turkish-holidays
  '((holiday-fixed  3 20   "Nevruz")
    (holiday-fixed  4 23   "Sovereignty and Children's Day")
    (holiday-fixed  5 19   "Day of Youth and Sport")
    (holiday-fixed  7 15   "\"Democracy\" Day")
    (holiday-fixed  8 30   "Victory Day")
    (holiday-fixed 10 29   "Republic Day")
    (holiday-fixed 11 10   "Death Anniversary of Atatürk")))

(defvar holiday-comestible-holidays
  '((holiday-fixed  3  1   "Icelandic Beer Day")
    (holiday-fixed  4  7   "American Beer Day")
    (holiday-fixed  4 19   "Bicycle Day")
    (holiday-fixed  4 20   "Cannabis Day")
    (holiday-fixed  4 21   "British Tea Day")
    (holiday-fixed  4 23   "German Beer Day")
    (holiday-fixed  6 15   "British Beer Day")
    (holiday-float  8 5  1 "Beer Day")
    (holiday-fixed  9 29   "Coffee Day")
    (holiday-fixed 12 15   "Tea Day")))

(defvar holiday-political-holidays
  '((holiday-fixed  1 27   "Holocaust Remembrance Day")
    (holiday-fixed  3  1   "Labour Day")
    (holiday-fixed  3  8   "Workingwomen's Day")
    (holiday-fixed  5 17   "Day Against Homophobia & Transphobia")
    (holiday-fixed  7 14   "Bastille Day")
    (holiday-fixed  9  1   "Suicide Prevention Day")
    (holiday-fixed 11 25   "Day for Elimination of Violence Against Women")))

(defvar holiday-misc-holidays
  '((holiday-fixed  3 14   "White Day")
    (holiday-fixed  3 14   "Black Day")
    (holiday-fixed  4 22   "Earth Day")
    (holiday-fixed  5 18   "Museum Day")
    (holiday-fixed  5 26   "Paper Aeroplane Day")
    (holiday-float  8 0  1 "Friendship Day")
    (holiday-fixed  9 19   "Talk Like a Pirate Day")
    (holiday-fixed  9 22   "Hobbit Day")
    (holiday-fixed  9 28   "Ask a Stupid Question Day")
    (holiday-fixed 10  9   "Post Day")
    (holiday-float 11 0  1 "Mischief Night")
    (holiday-fixed 11  1   "All Hallows' Day")
    (holiday-fixed 11  1   "All Souls' Day")
    (holiday-fixed 11 17   "Students' Day")
    (holiday-fixed 11 25   "Buy Nothing Day")
    (holiday-fixed 12 23   "Festivus")))
